### ISSUE TITLE
We should put a try/catch here

### ISSUE THREAD

**Issue by fischjup** [Leanplum/Leanplum-Segment-Android#5]
https://github.com/Leanplum/Leanplum-Segment-Android/blob/master/LeanplumIntegration/src/main/java/com/leanplum/segment/LeanplumIntegration.java#L83

**Comment by GiarcEnoredlac** [comment]
@fischjup @benmarten looks like Milos had a fix in a separate branch - https://github.com/Leanplum/Leanplum-Segment-Android/commit/656d69b259607aa9f97c91a48842340447f5c958

**Comment by benmarten** [comment]
Resolved by: https://github.com/Leanplum/Leanplum-Segment-Android/releases/tag/1.1.1
